default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/shopify_inventory_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_TEST", "postgresql://postgres:postgres@localhost:5432/shopify_inventory_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
